### ISSUE TITLE
add clear guidelines for third parties wishing to Contribute to the software

### ISSUE THREAD

**Issue by joethorley** [terrytangyuan/dml#26]
this is on the checklist for the JOSS review

please add to the README (ideally with a code of conduct)

**Comment by joethorley** [comment]
https://github.com/openjournals/joss-reviews/issues/1036

**Comment by road2stat** [comment]
-thanks! [Contributing Guidelines](https://github.com/terrytangyuan/dml/blob/master/CONTRIBUTING.md) and [Contributor Code of Conduct](https://github.com/terrytangyuan/dml/blob/master/CODE_OF_CONDUCT.md) for this package has been added and properly linked in [README](https://github.com/terrytangyuan/dml#contribute--code-of-conduct).
