### ISSUE TITLE
add documentation for `?dml`

### ISSUE THREAD

**Issue by joethorley** [terrytangyuan/dml#29]
can you `usethis::use_package_doc()` to add documentation for `?dml`

**Comment by joethorley** [comment]
https://github.com/openjournals/joss-reviews/issues/1036

**Comment by road2stat** [comment]
-good catch! Fixed with my own template for this purpose, check out https://github.com/terrytangyuan/dml/commit/55aaf65d013131c244e48a86120f5552594d10c4.
